# ======================================================
# ConfigMap - Fluent Bit (S3 ALB Access Log 전용)
# ======================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-s3-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    info
        Daemon       off
        Parsers_File parsers.conf

    @INCLUDE input.conf
    @INCLUDE output.conf

  input.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            cri
        Tag               kube.*
        Refresh_Interval  5
        Skip_Long_Lines   On

  output.conf: |
    [OUTPUT]
        Name              s3
        Match             *
        bucket            my-log-bucket-name
        region            us-east-1
        total_file_size   50M
        upload_timeout    1m
        s3_key_format     /k8s-logs/%Y/%m/%d/%H/%M/%S-$UUID.gz
        compression       gzip

  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

---
# ======================================================
# Deployment - Fluent Bit (S3 Reader 전용)
# ======================================================
aapiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit-s3
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentbit-s3
  template:
    metadata:
      labels:
        app: fluentbit-s3
    spec:
      serviceAccountName: fluentbit-s3
      containers:
        - name: fluent-bit
          image: amazon/aws-for-fluent-bit:2.31.12
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config
              mountPath: /fluent-bit/etc
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config
          configMap:
            name: fluentbit-s3-config
