kind: DaemonSet

image:
  repository: 635014547592.dkr.ecr.ap-northeast-2.amazonaws.com/fluentd
  tag: "1.0.0"
  pullPolicy: IfNotPresent


env:
  - name: FLUENT_ELASTICSEARCH_HOST
    value: elasticsearch
  - name: FLUENT_ELASTICSEARCH_PORT
    value: "9200"
  - name: FLUENT_ELASTICSEARCH_SCHEME
    value: http
  - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
    value: json

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 400Mi

tolerations:
  - operator: Exists
