name: Build & Push Elasticsearch Image (S3 Snapshot)

on:
  push:
    branches: [ "main" ]
    paths:
      - "obs/elasticsearch/image/**"

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: elasticsearch
  IMAGE_TAG: 7.17.16
  AWS_ACCOUNT_ID: 635014547592

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::635014547592:role/GitHubActionsECRRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t $ECR_REPOSITORY:${IMAGE_TAG} \
            obs/elasticsearch/image

      - name: Tag image
        run: |
          docker tag \
            $ECR_REPOSITORY:${IMAGE_TAG} \
            $AWS_ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:${IMAGE_TAG}

      - name: Push image to ECR
        run: |
          docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:${IMAGE_TAG}
