name: fluentd-no-build

on:
  push:
    paths:
      - "obs/fluentd/**"
      - ".github/workflows/fluentd-ecr.yml"

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: No image build (using official fluent-bit image)
        run: |
          echo "Docker build disabled. Using official Fluent Bit image."
