name: Build & Push Fluentd to ECR

on:
  push:
    paths:
      - "obs/fluentd/**"
      - ".github/workflows/fluentd-ecr.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # ðŸ”´ ìˆ˜ì •

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          docker build -t fluentd:1.0.0 ./obs/fluentd/image

      - name: Tag image
        run: |
          docker tag fluentd:1.0.0 \
            635014547592.dkr.ecr.us-east-1.amazonaws.com/fluentd:1.0.0

      - name: Push image
        run: |
          docker push \
            635014547592.dkr.ecr.us-east-1.amazonaws.com/fluentd:1.0.0
